server:
  host: "0.0.0.0"
  port: 8080

database:
  driver: "sqlite"
  host: ""
  port: 0
  username: ""
  password: ""
  database: "./test.db"
  ssl_mode: ""

storage:
  type: "local"
  local_path: "./storage"

auth:
  jwt_secret: "test-secret-key-for-development-only"
  oauth_server: "http://dex:5556"
  realms:
    - name: "admins"
      permissions: ["admin"]
    - name: "readonly"
      permissions: ["read"]
  oidc:
    client_id: "ganje"
    client_secret: "ganje-secret"
    redirect_uri: "http://localhost:4200/auth/callback"

logging:
  level: "info"
  format: "json"
  output: "stdout"

metrics:
  enabled: true
  path: "/metrics"
  separate_server: false
  port: 9090

messaging:
  rabbitmq:
    enabled: false
    url: ""
    exchange: ""
    exchange_type: ""
    routing_key: ""

webhook:
  enabled: false
  workers: 1
  max_retries: 3
  initial_backoff_ms: 1000
  max_backoff_ms: 30000
  http_timeout_ms: 10000

repositories:
  - name: "maven-local"
    type: "local"
    artifact_type: "maven"
    
  - name: "npm-local"
    type: "local"
    artifact_type: "npm"

  - name: "generic-local"
    type: "local"
    artifact_type: "generic"
