apiVersion: v1
kind: Service
metadata:
  name: {{ include "ganje.fullname" . }}
  labels:
    {{- include "ganje.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if and .Values.metrics.enabled .Values.metrics.separateServer }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "ganje.selectorLabels" . | nindent 4 }}
