image:
  repository: ghcr.io/your-org/admin-portal
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

backend:
  host: ganje-backend
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: admin.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
