issuer: http://dex:5556

storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db

web:
  http: 0.0.0.0:5556

staticClients:
- id: ganje-admin-portal
  redirectURIs:
  - 'http://localhost:4200/auth/callback'
  - 'http://admin-portal:4200/auth/callback'
  name: 'Ganje Admin Portal'
  secret: ZXhhbXBsZS1hZG1pbi1zZWNyZXQ

- id: ganje-backend
  redirectURIs:
  - 'http://localhost:8080/auth/callback'
  - 'http://backend:8080/auth/callback'
  name: 'Ganje Backend'
  secret: ZXhhbXBsZS1iYWNrZW5kLXNlY3JldA

enablePasswordDB: true

staticPasswords:
- email: "admin@ganje.local"
  # bcrypt hash of "admin123"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

- email: "developer@ganje.local"
  # bcrypt hash of "dev123"
  hash: "$2a$10$33EMT0cVYVlPy6WAMCLsceLYjWhuHpbz5yuZxu/GAFj03J9Lh.LGS"
  username: "developer"
  userID: "41331323-6f44-45e6-b3b9-2c4b8b6bb778"

oauth2:
  skipApprovalScreen: true
  alwaysShowLoginScreen: false

connectors:
- type: mockCallback
  id: mock
  name: Example
  config:
    username: "admin"
    groups: ["admins", "developers"]
