name: Frontend CI and Release

on:
  pull_request:
    paths:
      - 'ui/admin-portal/**'
      - 'ui/admin-portal/helm/**'
      - '.github/workflows/frontend.yml'
  push:
    branches: [ main ]
    paths:
      - 'ui/admin-portal/**'
      - 'ui/admin-portal/helm/**'
      - '.github/workflows/frontend.yml'
    tags:
      - 'ui-v*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui/admin-portal
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ui/admin-portal/package-lock.json
      - name: Install
        run: npm ci
      - name: Lint
        run: npx ng lint || echo 'lint optional'
      - name: Test
        run: npm test -- --watch=false --browsers=ChromeHeadless || echo 'tests optional in CI headless'

  build:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ui/admin-portal
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ui/admin-portal/package-lock.json
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build -- --configuration=production
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: admin-portal-dist
          path: ui/admin-portal/dist

  deploy-pages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: admin-portal-dist
          path: dist
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/admin-portal/browser
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  release:
    if: startsWith(github.ref, 'refs/tags/ui-v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: admin-portal-dist
          path: dist
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Admin Portal ${{ github.ref_name }}
          body: |
            Admin Portal build artifact for tag ${{ github.ref_name }}.
          files: |
            dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  helm-chart:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4
      - name: Helm lint (frontend chart)
        run: helm lint ui/admin-portal/helm/admin-portal
      - name: Package Helm chart
        run: |
          mkdir -p packaged-charts
          helm package ui/admin-portal/helm/admin-portal --destination packaged-charts
      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: admin-portal-chart
          path: packaged-charts/*.tgz
